Transpile and build one distributable
baethon/munci pull request #4
Opened 2019-10-18 12:11 UTC by Joxtacy

Add webpack and babel to transpile and build into one distributable
file.
This also minifies the bundle.

### Changes
Moved `index.js` and `emojilib.json` to `src/`.
Added webpack to build into a bundle and babel to transpile.
Bundle is in `dist/index.js`.
Points `main` in `package.json` to `dist/index.js`.

Task #1

2019-10-18 12:12 UTC, Joxtacy commented
@radmen 
Please take a look at this and let me know what you think. Is this what you wanted? If not, let me know what I can do better. :)

2019-10-18 12:13 UTC, Joxtacy commented
And I just realised that I broke the Travis build. Not sure what I can do about that. Will look into it as soon as I can though.

2019-10-19 09:06 UTC, radmen requested changes
Thank you for this MR. I really appreciate it!

I've noticed a couple of things:
- I'm not able to `require` the generated bundle in the Node env (didn't test it in the browser)
  - most likely this is the reason why the tests failed
- by moving the files to `src/` the `build:emojislib` script is broken
- I'd like to keep the original index file as a `main` entrypoint for the package. The dist files are meant to be used in environments which can't consume the original source file.

2019-10-19 09:06 UTC, radmen commented on webpack.config.js
> +            filename: "[name].js",
This should be a UMD export.

Adding this lines should be enough:

```
 library: 'munci',
 libraryTarget: 'umd',
```

2019-10-19 09:23 UTC, radmen commented
Out of curiosity, I've checked how Webpack makes the UMD builds. Apparently, this is [bugged](https://github.com/webpack/webpack/issues/6522) and such build can't be used in the Node env. Fortunately, there are some [workarounds](https://www.npmjs.com/package/webpack-global-object-x) for that.

2019-10-23 17:28 UTC, Joxtacy commented
Sorry. I've been really busy lately with work. But I'll get back on this again by the weekend. Sorry for letting you wait. 
And thanks for your input on this! I guess I needed the clarification. :)

2019-10-23 18:16 UTC, radmen commented
No worries, everything is fine :)

Thanks for the help!

2025-10-21 12:31 UTC, closed without merging